version: '3'
services:
  dorramk:
    container_name: dorramk
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 0000
    volumes:
        - /home/mysql/data:/var/lib/mysql
  spring_app:
    image: dorramk/my_devops
    container_name: tpachat
    restart: on-failure
    ports:
      - 9090:8089
    depends_on:
        - dorramk

  


