version: '3'
services:
  wissalbr:
    container_name: wissalbr
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 0000
    volumes:
        - /home/mysql/data:/var/lib/mysql
  spring_app:
    image: wissalbenrhouma/devops_project
    container_name: tpachat
    restart: on-failure
    ports:
      - 9092:9092
    depends_on:
        - wissalbr
